
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_Management.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bill
{

    public int BillID { get; set; }

    public Nullable<int> BookingID { get; set; }

    public Nullable<int> StaffID { get; set; }

    public Nullable<decimal> Total { get; set; }

    public Nullable<System.DateTime> PaymentDate { get; set; }

    public string PaymentMethod { get; set; }



    public virtual Booking Booking { get; set; }

    public virtual Staff Staff { get; set; }

}

}
