
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_Management.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Booking()
    {

        this.Bills = new HashSet<Bill>();

    }


    public int BookingID { get; set; }

    public Nullable<int> CustomerID { get; set; }

    public Nullable<int> RoomID { get; set; }

    public Nullable<System.DateTime> CheckInDate { get; set; }

    public Nullable<System.DateTime> CheckOutDate { get; set; }

    public Nullable<int> NumberAdult { get; set; }

    public Nullable<int> NumberChild { get; set; }

    public Nullable<decimal> TotalPrice { get; set; }

    public string BookingStatus { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Bill> Bills { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Room Room { get; set; }

}

}
