//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floor
    {
        public int FloorID { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public Nullable<int> FloorNumber { get; set; }
        public int TotalRoomsOfFloor { get; set; }
    
        public virtual Building Building { get; set; }
    }
}
