
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel_Management.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MonthlyRevenue
{

    public int RevenueID { get; set; }

    public System.DateTime RevenueMonth { get; set; }

    public decimal TotalRevenue { get; set; }

    public int TotalBills { get; set; }

    public string Note { get; set; }

}

}
